/* Autogenerated file. Do not edit manually. */

/* tslint:disable */

/* eslint-disable */
import type { TypedEventFilter, TypedEvent, TypedListener } from "./common";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
  BaseContract,
  ContractTransaction,
  Overrides,
  CallOverrides,
} from "ethers";

interface BuyFacetInterface extends ethers.utils.Interface {
  functions: {
    "executeBTD(uint256,uint80,uint80,uint80,uint80,(address,bytes))": FunctionFragment;
    "executeBuy(uint256,(address,bytes))": FunctionFragment;
    "executeBuyTwap(uint256,(address,bytes))": FunctionFragment;
    "executionBuyAmount(bool,uint256)": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "executeBTD",
    values: [
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      { dex: string; callData: BytesLike }
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "executeBuy",
    values: [BigNumberish, { dex: string; callData: BytesLike }]
  ): string;
  encodeFunctionData(
    functionFragment: "executeBuyTwap",
    values: [BigNumberish, { dex: string; callData: BytesLike }]
  ): string;
  encodeFunctionData(
    functionFragment: "executionBuyAmount",
    values: [boolean, BigNumberish]
  ): string;

  decodeFunctionResult(functionFragment: "executeBTD", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "executeBuy", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "executeBuyTwap",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "executionBuyAmount",
    data: BytesLike
  ): Result;

  events: {
    "AssetSwapped(address,address,address,uint256,uint256,address)": EventFragment;
    "BTDExecuted(uint256,uint256,uint256,uint256,uint256)": EventFragment;
    "BuyExecuted(uint256,uint256,uint256,uint256,uint256)": EventFragment;
    "BuyTwapExecuted(uint256,uint256,uint256,uint256,uint256,uint256)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "AssetSwapped"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "BTDExecuted"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "BuyExecuted"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "BuyTwapExecuted"): EventFragment;
}

export type AssetSwappedEvent = TypedEvent<
  [string, string, string, BigNumber, BigNumber, string] & {
    dex: string;
    fromAsset: string;
    toAsset: string;
    fromAmount: BigNumber;
    receivedAmount: BigNumber;
    account: string;
  }
>;

export type BTDExecutedEvent = TypedEvent<
  [BigNumber, BigNumber, BigNumber, BigNumber, BigNumber] & {
    strategyId: BigNumber;
    price: BigNumber;
    slippage: BigNumber;
    investTokenAmount: BigNumber;
    exchangeRate: BigNumber;
  }
>;

export type BuyExecutedEvent = TypedEvent<
  [BigNumber, BigNumber, BigNumber, BigNumber, BigNumber] & {
    strategyId: BigNumber;
    price: BigNumber;
    slippage: BigNumber;
    investTokenAmount: BigNumber;
    exchangeRate: BigNumber;
  }
>;

export type BuyTwapExecutedEvent = TypedEvent<
  [BigNumber, BigNumber, BigNumber, BigNumber, BigNumber, BigNumber] & {
    strategyId: BigNumber;
    price: BigNumber;
    slippage: BigNumber;
    investTokenAmount: BigNumber;
    exchangeRate: BigNumber;
    time: BigNumber;
  }
>;

export class BuyFacet extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  listeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter?: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): Array<TypedListener<EventArgsArray, EventArgsObject>>;
  off<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  on<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  once<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeListener<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeAllListeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): this;

  listeners(eventName?: string): Array<Listener>;
  off(eventName: string, listener: Listener): this;
  on(eventName: string, listener: Listener): this;
  once(eventName: string, listener: Listener): this;
  removeListener(eventName: string, listener: Listener): this;
  removeAllListeners(eventName?: string): this;

  queryFilter<EventArgsArray extends Array<any>, EventArgsObject>(
    event: TypedEventFilter<EventArgsArray, EventArgsObject>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEvent<EventArgsArray & EventArgsObject>>>;

  interface: BuyFacetInterface;

  functions: {
    executeBTD(
      strategyId: BigNumberish,
      fromInvestRoundId: BigNumberish,
      fromStableRoundId: BigNumberish,
      toInvestRoundId: BigNumberish,
      toStableRoundId: BigNumberish,
      swap: { dex: string; callData: BytesLike },
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    executeBuy(
      strategyId: BigNumberish,
      swap: { dex: string; callData: BytesLike },
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    executeBuyTwap(
      strategyId: BigNumberish,
      swap: { dex: string; callData: BytesLike },
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    executionBuyAmount(
      stableAmount: boolean,
      strategyId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;
  };

  executeBTD(
    strategyId: BigNumberish,
    fromInvestRoundId: BigNumberish,
    fromStableRoundId: BigNumberish,
    toInvestRoundId: BigNumberish,
    toStableRoundId: BigNumberish,
    swap: { dex: string; callData: BytesLike },
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  executeBuy(
    strategyId: BigNumberish,
    swap: { dex: string; callData: BytesLike },
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  executeBuyTwap(
    strategyId: BigNumberish,
    swap: { dex: string; callData: BytesLike },
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  executionBuyAmount(
    stableAmount: boolean,
    strategyId: BigNumberish,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  callStatic: {
    executeBTD(
      strategyId: BigNumberish,
      fromInvestRoundId: BigNumberish,
      fromStableRoundId: BigNumberish,
      toInvestRoundId: BigNumberish,
      toStableRoundId: BigNumberish,
      swap: { dex: string; callData: BytesLike },
      overrides?: CallOverrides
    ): Promise<void>;

    executeBuy(
      strategyId: BigNumberish,
      swap: { dex: string; callData: BytesLike },
      overrides?: CallOverrides
    ): Promise<void>;

    executeBuyTwap(
      strategyId: BigNumberish,
      swap: { dex: string; callData: BytesLike },
      overrides?: CallOverrides
    ): Promise<void>;

    executionBuyAmount(
      stableAmount: boolean,
      strategyId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;
  };

  filters: {
    "AssetSwapped(address,address,address,uint256,uint256,address)"(
      dex?: null,
      fromAsset?: null,
      toAsset?: null,
      fromAmount?: null,
      receivedAmount?: null,
      account?: null
    ): TypedEventFilter<
      [string, string, string, BigNumber, BigNumber, string],
      {
        dex: string;
        fromAsset: string;
        toAsset: string;
        fromAmount: BigNumber;
        receivedAmount: BigNumber;
        account: string;
      }
    >;

    AssetSwapped(
      dex?: null,
      fromAsset?: null,
      toAsset?: null,
      fromAmount?: null,
      receivedAmount?: null,
      account?: null
    ): TypedEventFilter<
      [string, string, string, BigNumber, BigNumber, string],
      {
        dex: string;
        fromAsset: string;
        toAsset: string;
        fromAmount: BigNumber;
        receivedAmount: BigNumber;
        account: string;
      }
    >;

    "BTDExecuted(uint256,uint256,uint256,uint256,uint256)"(
      strategyId?: BigNumberish | null,
      price?: null,
      slippage?: null,
      investTokenAmount?: null,
      exchangeRate?: null
    ): TypedEventFilter<
      [BigNumber, BigNumber, BigNumber, BigNumber, BigNumber],
      {
        strategyId: BigNumber;
        price: BigNumber;
        slippage: BigNumber;
        investTokenAmount: BigNumber;
        exchangeRate: BigNumber;
      }
    >;

    BTDExecuted(
      strategyId?: BigNumberish | null,
      price?: null,
      slippage?: null,
      investTokenAmount?: null,
      exchangeRate?: null
    ): TypedEventFilter<
      [BigNumber, BigNumber, BigNumber, BigNumber, BigNumber],
      {
        strategyId: BigNumber;
        price: BigNumber;
        slippage: BigNumber;
        investTokenAmount: BigNumber;
        exchangeRate: BigNumber;
      }
    >;

    "BuyExecuted(uint256,uint256,uint256,uint256,uint256)"(
      strategyId?: BigNumberish | null,
      price?: null,
      slippage?: null,
      investTokenAmount?: null,
      exchangeRate?: null
    ): TypedEventFilter<
      [BigNumber, BigNumber, BigNumber, BigNumber, BigNumber],
      {
        strategyId: BigNumber;
        price: BigNumber;
        slippage: BigNumber;
        investTokenAmount: BigNumber;
        exchangeRate: BigNumber;
      }
    >;

    BuyExecuted(
      strategyId?: BigNumberish | null,
      price?: null,
      slippage?: null,
      investTokenAmount?: null,
      exchangeRate?: null
    ): TypedEventFilter<
      [BigNumber, BigNumber, BigNumber, BigNumber, BigNumber],
      {
        strategyId: BigNumber;
        price: BigNumber;
        slippage: BigNumber;
        investTokenAmount: BigNumber;
        exchangeRate: BigNumber;
      }
    >;

    "BuyTwapExecuted(uint256,uint256,uint256,uint256,uint256,uint256)"(
      strategyId?: BigNumberish | null,
      price?: null,
      slippage?: null,
      investTokenAmount?: null,
      exchangeRate?: null,
      time?: null
    ): TypedEventFilter<
      [BigNumber, BigNumber, BigNumber, BigNumber, BigNumber, BigNumber],
      {
        strategyId: BigNumber;
        price: BigNumber;
        slippage: BigNumber;
        investTokenAmount: BigNumber;
        exchangeRate: BigNumber;
        time: BigNumber;
      }
    >;

    BuyTwapExecuted(
      strategyId?: BigNumberish | null,
      price?: null,
      slippage?: null,
      investTokenAmount?: null,
      exchangeRate?: null,
      time?: null
    ): TypedEventFilter<
      [BigNumber, BigNumber, BigNumber, BigNumber, BigNumber, BigNumber],
      {
        strategyId: BigNumber;
        price: BigNumber;
        slippage: BigNumber;
        investTokenAmount: BigNumber;
        exchangeRate: BigNumber;
        time: BigNumber;
      }
    >;
  };

  estimateGas: {
    executeBTD(
      strategyId: BigNumberish,
      fromInvestRoundId: BigNumberish,
      fromStableRoundId: BigNumberish,
      toInvestRoundId: BigNumberish,
      toStableRoundId: BigNumberish,
      swap: { dex: string; callData: BytesLike },
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    executeBuy(
      strategyId: BigNumberish,
      swap: { dex: string; callData: BytesLike },
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    executeBuyTwap(
      strategyId: BigNumberish,
      swap: { dex: string; callData: BytesLike },
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    executionBuyAmount(
      stableAmount: boolean,
      strategyId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    executeBTD(
      strategyId: BigNumberish,
      fromInvestRoundId: BigNumberish,
      fromStableRoundId: BigNumberish,
      toInvestRoundId: BigNumberish,
      toStableRoundId: BigNumberish,
      swap: { dex: string; callData: BytesLike },
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    executeBuy(
      strategyId: BigNumberish,
      swap: { dex: string; callData: BytesLike },
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    executeBuyTwap(
      strategyId: BigNumberish,
      swap: { dex: string; callData: BytesLike },
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    executionBuyAmount(
      stableAmount: boolean,
      strategyId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;
  };
}
