/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
  BaseContract,
  ContractTransaction,
  Overrides,
  CallOverrides,
} from "ethers";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";
import type { TypedEventFilter, TypedEvent, TypedListener } from "./common";

interface FloorFacetInterface extends ethers.utils.Interface {
  functions: {
    "executeFloor(uint256,(address,bytes))": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "executeFloor",
    values: [BigNumberish, { dex: string; callData: BytesLike }]
  ): string;

  decodeFunctionResult(
    functionFragment: "executeFloor",
    data: BytesLike
  ): Result;

  events: {
    "AssetSwapped(address,address,address,uint256,uint256,address)": EventFragment;
    "FloorExecuted(uint256,uint256,uint256,uint256,uint256)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "AssetSwapped"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "FloorExecuted"): EventFragment;
}

export type AssetSwappedEvent = TypedEvent<
  [string, string, string, BigNumber, BigNumber, string] & {
    dex: string;
    fromAsset: string;
    toAsset: string;
    fromAmount: BigNumber;
    receivedAmount: BigNumber;
    account: string;
  }
>;

export type FloorExecutedEvent = TypedEvent<
  [BigNumber, BigNumber, BigNumber, BigNumber, BigNumber] & {
    strategyId: BigNumber;
    price: BigNumber;
    slippage: BigNumber;
    stableTokenAmount: BigNumber;
    exchangeRate: BigNumber;
  }
>;

export class FloorFacet extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  listeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter?: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): Array<TypedListener<EventArgsArray, EventArgsObject>>;
  off<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  on<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  once<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeListener<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeAllListeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): this;

  listeners(eventName?: string): Array<Listener>;
  off(eventName: string, listener: Listener): this;
  on(eventName: string, listener: Listener): this;
  once(eventName: string, listener: Listener): this;
  removeListener(eventName: string, listener: Listener): this;
  removeAllListeners(eventName?: string): this;

  queryFilter<EventArgsArray extends Array<any>, EventArgsObject>(
    event: TypedEventFilter<EventArgsArray, EventArgsObject>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEvent<EventArgsArray & EventArgsObject>>>;

  interface: FloorFacetInterface;

  functions: {
    executeFloor(
      strategyId: BigNumberish,
      dexSwap: { dex: string; callData: BytesLike },
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;
  };

  executeFloor(
    strategyId: BigNumberish,
    dexSwap: { dex: string; callData: BytesLike },
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  callStatic: {
    executeFloor(
      strategyId: BigNumberish,
      dexSwap: { dex: string; callData: BytesLike },
      overrides?: CallOverrides
    ): Promise<void>;
  };

  filters: {
    "AssetSwapped(address,address,address,uint256,uint256,address)"(
      dex?: null,
      fromAsset?: null,
      toAsset?: null,
      fromAmount?: null,
      receivedAmount?: null,
      account?: null
    ): TypedEventFilter<
      [string, string, string, BigNumber, BigNumber, string],
      {
        dex: string;
        fromAsset: string;
        toAsset: string;
        fromAmount: BigNumber;
        receivedAmount: BigNumber;
        account: string;
      }
    >;

    AssetSwapped(
      dex?: null,
      fromAsset?: null,
      toAsset?: null,
      fromAmount?: null,
      receivedAmount?: null,
      account?: null
    ): TypedEventFilter<
      [string, string, string, BigNumber, BigNumber, string],
      {
        dex: string;
        fromAsset: string;
        toAsset: string;
        fromAmount: BigNumber;
        receivedAmount: BigNumber;
        account: string;
      }
    >;

    "FloorExecuted(uint256,uint256,uint256,uint256,uint256)"(
      strategyId?: BigNumberish | null,
      price?: null,
      slippage?: null,
      stableTokenAmount?: null,
      exchangeRate?: null
    ): TypedEventFilter<
      [BigNumber, BigNumber, BigNumber, BigNumber, BigNumber],
      {
        strategyId: BigNumber;
        price: BigNumber;
        slippage: BigNumber;
        stableTokenAmount: BigNumber;
        exchangeRate: BigNumber;
      }
    >;

    FloorExecuted(
      strategyId?: BigNumberish | null,
      price?: null,
      slippage?: null,
      stableTokenAmount?: null,
      exchangeRate?: null
    ): TypedEventFilter<
      [BigNumber, BigNumber, BigNumber, BigNumber, BigNumber],
      {
        strategyId: BigNumber;
        price: BigNumber;
        slippage: BigNumber;
        stableTokenAmount: BigNumber;
        exchangeRate: BigNumber;
      }
    >;
  };

  estimateGas: {
    executeFloor(
      strategyId: BigNumberish,
      dexSwap: { dex: string; callData: BytesLike },
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    executeFloor(
      strategyId: BigNumberish,
      dexSwap: { dex: string; callData: BytesLike },
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;
  };
}
